[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lumina"
version = "0.1.0"
description = "LUMINA: A Large-scale Unified Model for Intelligent Grid Applications"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE.md"}
authors = [
  {name = "Argonne LUMINA Team", email = "kimk@anl.gov"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Copyright :: 2025 :: Argonne National Laboratory",
]
dependencies = [
    # core dependencies
    "torch>=2.9.1",
    "torch-geometric>=2.7.0",
    "numpy",
    "pandas",
    "scipy",
    "networkx",
    "joblib",
    "pyyaml",
    "h5py",
    "pydantic"
]

[project.urls]
"Homepage" = "https://github.com/argonne-gridfm/lumina-core"
"Bug Tracker" = "https://github.com/argonne-gridfm/lumina-core/issues"

# This section helps setuptools find your package automatically
[tool.setuptools.packages.find]
include = ["lumina*"]

# Optional dependencies for extra features
[project.optional-dependencies]
# pip install -e .[test]
test = [
    "pytest"
]

# `pip install -e ".[cuGraph]"` (add the PyG wheel index for your torch/CUDA build if needed)
cuGraph = [
  "pyg-lib"
]

# `pip install -e .[dev]`
dev = [
    "ipykernel"
]

# `pip install -e .[acopf]`
acopf = [
    "pandapower",
    "matpowercaseframes",
    "pypower",
    "pyjulia", # for Julia solver
    "julia", # for Julia IPOPT solver
    "numba", # acceleration in Python Interior Point Solver PIPS
]

# `pip install -e .[hps]`
hps = [
    "wandb",
    "optuna",
]

# `pip install -e .[doc]`
doc = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints"
]

# `pip install -e .[benchmark]`
benchmark = [
    "lightning",
]

# `pip install -e ".[all]"`
all = [
    "torch",
    "torch-geometric",
    "pyg-lib",
    "numpy",
    "pandas",
    "scipy",
    "joblib",
    "pytest",
    "ipykernel",
    "pandapower",
    "matpowercaseframes",
    "pypower",
    "pyjulia",
    "julia",
    "numba",
    "wandb",
    "optuna",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints",
    "lightning",
    "pyyaml",
]
