wandb_version: 1

case:
  value: case14
loader.batch_size:
  value: 64
loss_type:
  value: augmented_lagrangian
model_type:
  value: RGAT
optimizer.Adam.lr:
  value: 0.0008856021227974524
optimizer.Adam.weight_decay:
  value: 1.00927245129318e-05
trainer.devices:
  value: 1
trainer.max_epochs:
  value: 50
trainer.num_nodes:
  value: 1
trainer.precision:
  value: 32-true
trainer.strategy:
  value: auto
wandb_project:
  value: lumina-opf
