---
root: "/pscratch/sd/k/kibaekk/datasets/"
logging_dir: "/global/cfs/cdirs/amsc004/lumina/logs/"
checkpoint_dir: "/global/cfs/cdirs/amsc004/lumina/ddp_checkpoints/"
optimizer:
  AdamW:
    lr: 1.0e-03
    betas: 
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.01
train_split: 0.8
val_split: 0.1
loader:
  batch_size: 256
  shuffle: true
  num_workers: 0
training:
  max_epochs: 10
  patience: 100000
  max_global_samples: 1000000
  global_batch_size: 8192
  score_alpha: 1.0
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1
  log_every_n_steps: 0
  log_every_n_samples: 8192
  val_every_n_epochs: 0
  val_every_n_samples: 16384
  throughput_enabled: false
  log_normalized_violation: false
checkpointing:
  monitor: "val/score"
  save_last: true
  every_n_epochs: 0
  every_n_samples: 0
