wandb_version: 1

case:
  value: case30
loader.batch_size:
  value: 64
loss_type:
  value: mse
model_type:
  value: HeteroGNN
optimizer.Adam.lr:
  value: 8.215618221505867e-05
optimizer.Adam.weight_decay:
  value: 4.6774954584835355e-06
trainer.devices:
  value: 1
trainer.max_epochs:
  value: 50
trainer.num_nodes:
  value: 1
trainer.precision:
  value: 32-true
trainer.strategy:
  value: auto
wandb_project:
  value: lumina-opf
