---
root: "/pscratch/sd/k/kibaekk/datasets/"
logging_dir: "/pscratch/sd/k/kibaekk/lumina/logs/"
checkpoint_dir: "/pscratch/sd/k/kibaekk/lumina/ddp_checkpoints/"
data:
  backend: "in_memory" # in_memory | on_disk
optimizer:
  AdamW:
    lr: 0.00010727816096895636 # HPO value
    betas: 
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 1.8407194842730544e-6 # HPO value
scheduler:
  type: "cosine"
  t_max: null
  eta_min: 0.0
train_split: 0.8
val_split: 0.1
loader:
  batch_size: 16
  shuffle: true
  num_workers: 8
  persistent_workers: true
  prefetch_factor: 4
  pin_memory: true
training:
  max_epochs: 10000000
  patience: 100000
  max_global_samples: 2000000
  global_batch_size: 64
  score_alpha: 1.0
  gradient_clip_val: 1.432284535312203 # HPO value
  gradient_clip_algorithm: "norm"
  accumulate_grad_batches: 1
  log_every_n_steps: 100
  log_every_n_samples: 0
  val_every_n_epochs: 0
  val_every_n_samples: 100000
  val_subset_samples: 0
  throughput_enabled: false
  log_normalized_violation: true
checkpointing:
  monitor: "val/score"
  save_last: true
  every_n_epochs: 0
  every_n_samples: 0
