command:
  - python
  - example/opf/train_opf.py
  - "--config=configs/config.yaml"
  - "--wandb"
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  wandb_project:
    value: lumina-opf
  case:
    values:
      - case14
      - case30
      - case57
  model_type:
    values:
      - HeteroGNN
  loss_type:
    values:
      - mse
      - augmented_lagrangian
  trainer.devices:
    values:
      - 1
  trainer.num_nodes:
    values:
      - 1
  trainer.precision:
    values:
      - "32-true"
  trainer.strategy:
    values:
      - "auto"
  trainer.max_epochs:
    values:
      - 50
      - 100
  optimizer.Adam.lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  optimizer.Adam.weight_decay:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.0001
  loader.batch_size:
    values:
      - 16
      - 32
      - 64
early_terminate:
  type: hyperband
  max_iter: 20
  s: 3
