command:
  - bash
  - -lc
  - ./scripts/perlmutter.launch.ddp.sh
method: bayes
metric:
  name: val/score
  goal: minimize
parameters:
  wandb_project:
    value: lumina-sweep
  model_type:
    values:
      - HeteroGNN
  loss_type:
    values:
      - mse
  optimizer.Adam.lr:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.001
  optimizer.Adam.weight_decay:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.0001
  loader.batch_size:
    values:
      - 16
      - 32
      - 64
  training.accumulate_grad_batches:
    values:
      - 1
      - 2
      - 4
      - 8
early_terminate:
  type: hyperband
  max_iter: 20
  s: 3
